export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        primary: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'float': 'float 3s ease-in-out infinite',
        'pulse-slow': 'pulseSlow 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        pulseSlow: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      boxShadow: {
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.07)',
        'card': '0 1px 3px rgba(0, 0, 0, 0.04), 0 1px 2px rgba(0, 0, 0, 0.06)',
        'card-hover': '0 12px 24px -8px rgba(79, 70, 229, 0.15)',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-blue-100',
    'bg-red-100',
    'bg-yellow-100',
    'bg-green-100',
    'bg-purple-100',
    'bg-gray-100',
    'text-blue-600',
    'text-red-600',
    'text-yellow-600',
    'text-green-600',
    'text-purple-600',
    'text-gray-600',
    'text-blue-800',
    'text-red-800',
    'text-yellow-800',
    'text-green-800',
    'text-purple-800',
    'text-gray-800',
    'border-blue-200',
    'border-red-200',
    'border-yellow-200',
    'border-green-200',
    'border-purple-200',
    'border-gray-200',
    'border-l-red-500',
    'border-l-yellow-500',
    'border-l-green-500',
    'border-l-gray-500',
    'stat-gradient-blue',
    'stat-gradient-green',
    'stat-gradient-orange',
    'stat-gradient-purple',
  ],
}
